branch-defaults:
  default:
    environment: Project3env-env
deploy:
  artifact: build.zip  
environment-defaults:
  final-env:
    branch: null
    repository: null
global:
  application_name: project3
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: 
  sc: null
  workspace_type: Application
